// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// densemlp_train_cpp
List densemlp_train_cpp(const arma::mat& X, const arma::mat& Y, Rcpp::IntegerVector hidden_units, int task, int output_dim, int epochs, int batch_size, double lr, double validation, bool early_stopping, int patience, double min_delta, int min_epochs, bool residual, bool gated, Rcpp::NumericVector dropout, bool interaction, bool batch_norm, int input_projection, double ema_decay, std::string lr_schedule, unsigned int seed, bool verbose, int survival_loss, Rcpp::NumericVector breaks_in, Rcpp::NumericVector ghat_grid_in);
RcppExport SEXP _densemlp_densemlp_train_cpp(SEXP XSEXP, SEXP YSEXP, SEXP hidden_unitsSEXP, SEXP taskSEXP, SEXP output_dimSEXP, SEXP epochsSEXP, SEXP batch_sizeSEXP, SEXP lrSEXP, SEXP validationSEXP, SEXP early_stoppingSEXP, SEXP patienceSEXP, SEXP min_deltaSEXP, SEXP min_epochsSEXP, SEXP residualSEXP, SEXP gatedSEXP, SEXP dropoutSEXP, SEXP interactionSEXP, SEXP batch_normSEXP, SEXP input_projectionSEXP, SEXP ema_decaySEXP, SEXP lr_scheduleSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP survival_lossSEXP, SEXP breaks_inSEXP, SEXP ghat_grid_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type hidden_units(hidden_unitsSEXP);
    Rcpp::traits::input_parameter< int >::type task(taskSEXP);
    Rcpp::traits::input_parameter< int >::type output_dim(output_dimSEXP);
    Rcpp::traits::input_parameter< int >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type validation(validationSEXP);
    Rcpp::traits::input_parameter< bool >::type early_stopping(early_stoppingSEXP);
    Rcpp::traits::input_parameter< int >::type patience(patienceSEXP);
    Rcpp::traits::input_parameter< double >::type min_delta(min_deltaSEXP);
    Rcpp::traits::input_parameter< int >::type min_epochs(min_epochsSEXP);
    Rcpp::traits::input_parameter< bool >::type residual(residualSEXP);
    Rcpp::traits::input_parameter< bool >::type gated(gatedSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type dropout(dropoutSEXP);
    Rcpp::traits::input_parameter< bool >::type interaction(interactionSEXP);
    Rcpp::traits::input_parameter< bool >::type batch_norm(batch_normSEXP);
    Rcpp::traits::input_parameter< int >::type input_projection(input_projectionSEXP);
    Rcpp::traits::input_parameter< double >::type ema_decay(ema_decaySEXP);
    Rcpp::traits::input_parameter< std::string >::type lr_schedule(lr_scheduleSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type survival_loss(survival_lossSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type breaks_in(breaks_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ghat_grid_in(ghat_grid_inSEXP);
    rcpp_result_gen = Rcpp::wrap(densemlp_train_cpp(X, Y, hidden_units, task, output_dim, epochs, batch_size, lr, validation, early_stopping, patience, min_delta, min_epochs, residual, gated, dropout, interaction, batch_norm, input_projection, ema_decay, lr_schedule, seed, verbose, survival_loss, breaks_in, ghat_grid_in));
    return rcpp_result_gen;
END_RCPP
}
// densemlp_predict_cpp
arma::mat densemlp_predict_cpp(const arma::mat& X, List weights, List biases, List gamma, List beta, List running_mean, List running_var, List residual_weights, List residual_biases, List gate_weights, List gate_biases, arma::vec interaction_weights, arma::vec interaction_biases, arma::mat proj_weights, arma::vec proj_biases, int task, bool residual, bool gated, bool interaction, bool batch_norm, int input_projection);
RcppExport SEXP _densemlp_densemlp_predict_cpp(SEXP XSEXP, SEXP weightsSEXP, SEXP biasesSEXP, SEXP gammaSEXP, SEXP betaSEXP, SEXP running_meanSEXP, SEXP running_varSEXP, SEXP residual_weightsSEXP, SEXP residual_biasesSEXP, SEXP gate_weightsSEXP, SEXP gate_biasesSEXP, SEXP interaction_weightsSEXP, SEXP interaction_biasesSEXP, SEXP proj_weightsSEXP, SEXP proj_biasesSEXP, SEXP taskSEXP, SEXP residualSEXP, SEXP gatedSEXP, SEXP interactionSEXP, SEXP batch_normSEXP, SEXP input_projectionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< List >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< List >::type biases(biasesSEXP);
    Rcpp::traits::input_parameter< List >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< List >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< List >::type running_mean(running_meanSEXP);
    Rcpp::traits::input_parameter< List >::type running_var(running_varSEXP);
    Rcpp::traits::input_parameter< List >::type residual_weights(residual_weightsSEXP);
    Rcpp::traits::input_parameter< List >::type residual_biases(residual_biasesSEXP);
    Rcpp::traits::input_parameter< List >::type gate_weights(gate_weightsSEXP);
    Rcpp::traits::input_parameter< List >::type gate_biases(gate_biasesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type interaction_weights(interaction_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type interaction_biases(interaction_biasesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type proj_weights(proj_weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type proj_biases(proj_biasesSEXP);
    Rcpp::traits::input_parameter< int >::type task(taskSEXP);
    Rcpp::traits::input_parameter< bool >::type residual(residualSEXP);
    Rcpp::traits::input_parameter< bool >::type gated(gatedSEXP);
    Rcpp::traits::input_parameter< bool >::type interaction(interactionSEXP);
    Rcpp::traits::input_parameter< bool >::type batch_norm(batch_normSEXP);
    Rcpp::traits::input_parameter< int >::type input_projection(input_projectionSEXP);
    rcpp_result_gen = Rcpp::wrap(densemlp_predict_cpp(X, weights, biases, gamma, beta, running_mean, running_var, residual_weights, residual_biases, gate_weights, gate_biases, interaction_weights, interaction_biases, proj_weights, proj_biases, task, residual, gated, interaction, batch_norm, input_projection));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_densemlp_densemlp_train_cpp", (DL_FUNC) &_densemlp_densemlp_train_cpp, 26},
    {"_densemlp_densemlp_predict_cpp", (DL_FUNC) &_densemlp_densemlp_predict_cpp, 21},
    {NULL, NULL, 0}
};

RcppExport void R_init_densemlp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
