# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

densemlp_train_cpp <- function(X, Y, hidden_units, task, output_dim, epochs, batch_size, lr, validation, early_stopping, patience, min_delta, min_epochs, residual, gated, dropout, interaction, batch_norm, input_projection, ema_decay, lr_schedule, seed, verbose, survival_loss, breaks_in, ghat_grid_in) {
    .Call(`_densemlp_densemlp_train_cpp`, X, Y, hidden_units, task, output_dim, epochs, batch_size, lr, validation, early_stopping, patience, min_delta, min_epochs, residual, gated, dropout, interaction, batch_norm, input_projection, ema_decay, lr_schedule, seed, verbose, survival_loss, breaks_in, ghat_grid_in)
}

densemlp_predict_cpp <- function(X, weights, biases, gamma, beta, running_mean, running_var, residual_weights, residual_biases, gate_weights, gate_biases, interaction_weights, interaction_biases, proj_weights, proj_biases, task, residual, gated, interaction, batch_norm, input_projection) {
    .Call(`_densemlp_densemlp_predict_cpp`, X, weights, biases, gamma, beta, running_mean, running_var, residual_weights, residual_biases, gate_weights, gate_biases, interaction_weights, interaction_biases, proj_weights, proj_biases, task, residual, gated, interaction, batch_norm, input_projection)
}

